name: skolarac
description: "Mobilni Školarac"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  gif: ^2.3.0
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/slike/
     - assets/avatari/
     - assets/zastave/
  fonts:
     - family: RoadRage
       fonts:
         - asset: assets/fontovi/RoadRage-Regular.ttf
     - family: Oswald
       fonts:
         - asset: assets/fontovi/Oswald-SemiBold.ttf
